### ISSUE TITLE
Nexus integration not working

### ISSUE THREAD

**Issue by Duuftus** [v4n00/h2mm-cli#53]
I followed the steps and entered the api key at the bottom of the page listed “personal api key”
It replied with “weird server reply” and “curl failed”

**Comment by v4n00** [comment]
Acknowledged, will work on it in ~15 hours as I have IRL stuff to deal with. In the meantime please provide a screenshot with what you are seeing so I can properly debug. Thanks!

**Comment by Duuftus** [comment]
![Image](https://github.com/user-attachments/assets/6068a4e2-4580-4bf0-bae2-320f117eb196)

**Comment by v4n00** [comment]
Can you try the following command:
`curl -H "apikey: API_HERE" "https://api.nexusmods.com/v1/users/validate.json"`
Replace API_HERE with your API key.

**Comment by Duuftus** [comment]
Im a little confused
Doci need the quotes and should i include that link in the command?

**Comment by v4n00** [comment]
Yes, you need the quotes and keep the link. Execute the entire command as you see it in the formatted box from the reply.

**Comment by Duuftus** [comment]
It returned with a bunch of my account details

**Comment by v4n00** [comment]
Hm so it works. Now let's try `curl -IH "apikey: API_HERE" "https://api.nexusmods.com/v1/users/validate.json"`
Should give you an HTTP 200 as the first line. If this works try the nexus setup again, it's very possible Nexus just had a stroke at the time you tried to set it up.

**Comment by Duuftus** [comment]
It had http/2 200
I tried it again anyways and had the same issue

**Comment by v4n00** [comment]
Will provide further troubleshooting steps tomorrow.

**Comment by v4n00** [comment]
Hi, I will give you a piece of code to run, this comes straight from the mod manager but adapted a bit to be able to output the relevant information, shouldn't output any identifiable information so I'd want you to give me a screenshot of what it outputs.

```bash
bash -c 'echo -ne "Enter your Nexus Mods API key: " >&2
read -e nexus_api_key

echo -ne "api_key: $nexus_api_key\n" >&2
[[ -z "$nexus_api_key" ]] && exit 1

statement="curl -IH \"apikey: $nexus_api_key\" -X GET \"https://api.nexusmods.com/v1/users/validate.json\""
echo -ne "statement: $statement\n" >&2

response=$(eval "$statement" | head -n 1)
echo -ne "response: $response\n" >&2'

```

**Comment by Duuftus** [comment]
Im not gonna be able to do more with this till later tmr since its my birthday tmr

**Comment by XxZaylienxX** [comment]
I've been having the same issue too, followed all the steps here and got the same results. I was just wondering if i could help by providing screenshots? I've got one for the last bit of code you put here.

![Image](https://github.com/user-attachments/assets/ae6feaf4-50d4-4a5b-b6fb-096710d35ee7)

**Comment by XxZaylienxX** [comment]
Alright I updated it and it accepted the API key bun now its erroring on the refresh of the desktop database as you can see in the screenshot

![Image](https://github.com/user-attachments/assets/0ee631d9-cb08-479d-ba28-e80e6b227dc9)

**Comment by v4n00** [comment]
Well, that's what happens when I only test on 1 machine. Forgot to add an argument to a command, fixed in 0.5.3test2, please do update and let me know if it works.

**Comment by XxZaylienxX** [comment]
Alright so now the setup seemingly works. But going to download any mod via mod manager says its working, sometimes brings up the option to select to open with H2MM but then does nothing and when it doesn't bring the option up it also seemingly does nothing. Honestly no idea what the error could be this time but loading up helldivers gave me these errors but after leaving it a while it fixed itself and I can now play

![20250515_133636.jpg](https://github.com/user-attachments/assets/a5054886-2d62-4c41-96ad-73fd28ab9070)

![20250515_133846.jpg](https://github.com/user-attachments/assets/3793b8e4-d91b-4aef-a244-6d9fedce9354)

**Comment by v4n00** [comment]
Not being able to connect to HD2 servers is in no way shape or form the mod manager's fault, at max it's the mods that you install but I don't believe that's the case, probably an issue with HD2 servers themselves. That is, unless you get these errors at startup consistently.

As for the integration not working, at least the setup is fixed now, but the integration itself should be working fine, the console window that pops up is supposed to stay open until you close it. Could you verify the mods got installed with `h2mm list`? Otherwise, could you screenshot what happens in case you get to select variants? From what I understand, it's probable that the console window closes way too fast and doesn't remain open (which shouldn't be the case).

Also, sorry for the constant troubles, I'm really grateful that you are taking time out of your day to help me debug this issue.

**Comment by XxZaylienxX** [comment]
Yeah thought the error was a server thing just thought i should mention it JIC.

The mods i tried installing never got installed. ill send you over links to the mods im using to test and i would love to send you a screen hot of whatever terminal you are on about but i cant see any at all. Now when i click download with mod manager, nexus does the count down but then absolutely nothing happens. ive tried re-updating it and setting it up again but still nothing with either of the mods. 

Also no worries, Im just happy to help with the troubleshooting cause this has helped me with modding this game so much i cant thank you enough ^-^

![Image](https://github.com/user-attachments/assets/c48561f1-775e-4874-9875-7ece54c88757)

![Image](https://github.com/user-attachments/assets/bc2ec118-730c-494a-a0e0-3c71b85e186d)

https://www.nexusmods.com/helldivers2/mods/790?tab=description 
https://www.nexusmods.com/helldivers2/mods/4725?tab=description

**Comment by v4n00** [comment]
Well, I've also had this problem **with Firefox** (I use a fork of it called Waterfox) and I just assumed it was a problem on my end since afaik Firefox is able to handle opening links, and I've tested it on Chrome and it works with no issues. Might have to look into why Firefox isn't interacting correctly but this might not be an issue related to the mod manager.

Would you mind testing this on Chrome to see if it works? In the meantime I'm gonna look over the Firefox issue. Thanks a bunch!

**Comment by XxZaylienxX** [comment]
Alight cool. I tried it in chrome this time its giving the popup every time now which is good but still not downloading. Ive also ran that code now and it did output h2mm as it should after i set it to but still no download and this other random pop up appeared that ill attach a screenshot of too. ive had plenty of issues with firefox in the past dont know how i always manage to forget how much it hates opening stuff lol

![Image](https://github.com/user-attachments/assets/58a06184-42a7-43e3-8f27-dad8de970d9c)

![Image](https://github.com/user-attachments/assets/fc46a8e1-6808-4f91-b510-46c27dbba67f)

![Image](https://github.com/user-attachments/assets/525e31f3-211c-4d31-adfb-4b4d27f229ae)

**Comment by v4n00** [comment]
What happens when you click on h2mm in the dialogue?

**Comment by XxZaylienxX** [comment]
sent you over a friend request now

**Comment by XxZaylienxX** [comment]
also clicking on h2mm doesn't do anything visually other than close the dialogue, but i assume its trying and failing to do something

**Comment by v4n00** [comment]
Did not receive a request, can you give me your username?

**Comment by XxZaylienxX** [comment]
xx_zaylien_xx

**Comment by v4n00** [comment]
Issue was with how the `h2mm.desktop` file was attempting to call h2mm, for some reason, konsole on Steam Deck refuses to inherit the used SHELL's environment variables and it wouldn't know where h2mm is installed.

Fixed by using absolute path and adding `%u` to the end to signify that's where the link should be placed.
